window:
  title: "Umamusume"
  scaling_factor: 1.5           # 150% DPI scaling
  client_offset: [6, 30]        # Offset from outer to client area (logical pixels)
  placement:
    x: 0
    y: 0
    width: 1920
    height: 1080

capture:
  split:
    left_pin_ratio: 0.07874    # Left pin area (discarded)
    primary_ratio: 0.42126     # Primary gameplay area
    menus_ratio: 0.50          # Menu/UI area