window:
  title: "Umamusume"
  scaling_factor: 1.5           # 150% DPI scaling
  # placement:                   # Optional: Uncomment to auto-position window at startup
  #   x: 0
  #   y: 0
  #   width: 1920
  #   height: 1080

# Measured values from client area
capture:
  split:
    left_pin_ratio: 0.07874    # Left pin area (discarded)
    primary_ratio: 0.42126     # Primary gameplay area
    menus_ratio: 0.41497       # Menu/UI area
    tabs_ratio: 0.08503        # Right-side tabs (clipped to separate image)
