window:
  title: "Umamusume"
  scaling_factor: 1.5           # 150% DPI scaling
  placement:
    x: 0
    y: 0
    width: 1920
# Putting the "correct" height here results in a bug that offsets click locations from pointer locations once the window is placed
# Must put a wrong height here to prevent this
    height: 1

# Measured values
capture:
  split:
    left_pin_ratio: 0.07874    # Left pin area (discarded)
    primary_ratio: 0.42126     # Primary gameplay area
    menus_ratio: 0.41497       # Menu/UI area
    tabs_ratio: 0.08503        # Right-side tabs (clipped to separate image)
